### ISSUE TITLE
When using jsonrecords format, some values get overwritten when cell keys are repeated

### ISSUE THREAD

**Issue by gemathus** [Datawheel/olap-client#5]
Hi, I'm not sure if this is a bug or if I'm missing an option,param in my query. 
The situation is this:
When executing query with format set as jsonrecords (default) some values get overwritten if som cell kets are repeated. This is hard to explain with words, so these two pictures should be of some help.
Using "json" format:

---

![json](https://user-images.githubusercontent.com/10574406/64567653-56305b00-d31e-11e9-81c6-6641199b0b49.png)

---

As we can see, the date drilldown values start at 2015 and go all the way up to 2019. The first element is "2015/1" for January 2015. 
This is the expected behavior, but something strange happens when outputting with format jsonrecords:

---

![jsonrecords](https://user-images.githubusercontent.com/10574406/64567745-8d067100-d31e-11e9-917e-986df275650a.png)

The measures are correct, but the month values get overwritten. I think this has something to do with the fact that all cell keys are values from [1,12]. Is there a way around this? I'm I missing something?

**Comment by frabarz** [comment]
This seems like an issue with the schema on the server-side. I think it's caused by the way the data is stored in the database, but in any case, it's not some missing parameter in the request.
This is in the DataChile cube, right? Can you give me the query URL?

**Comment by gemathus** [comment]
Thank you for your reply, @frabarz .

It's actually a project of my own, but I based my cube design on the DataChile Cube. And I'm also using the datachile-mondrian repo to run my server. It's a prety small cube (just looking at crimes by type, date and location).


I think that if you take a look at my `schema.xml`  that should be enough for you to spot if something is wrong. (It's a small schema). As you'll see, my public date dimension is exactly the same that in the Datachile Cube.
~~~~xml
<Schema name="datamex">
    <Dimension name="Date" type="TimeDimension">
        <Hierarchy hasAll="true" primaryKey="id">
            <Table name="dim_date" schema="public" />
            <Level column="the_year" levelType="TimeYears" name="Year" type="Numeric" uniqueMembers="true" />
            <Level column="month_of_year" levelType="TimeMonths" name="Month" type="Numeric" uniqueMembers="false">
                <CaptionExpression>
                    <SQL>
                        <![CDATA[(the_year || '/' || month_of_year)]]>
                    </SQL>
                </CaptionExpression>
            </Level>
            <Level column="day_of_month" levelType="TimeDays" name="Day" type="Numeric" uniqueMembers="false" />
        </Hierarchy>
    </Dimension>
    <Dimension name="Geography">
        <Annotations>
            <Annotation name="index_as">geo</Annotation>
        </Annotations>
        <Hierarchy hasAll="true" primaryKey="municipality_id">
            <Table name="dim_municipality" schema="public" />
            <Level column="state_id" name="State" nameColumn="state_name" uniqueMembers="true" />
            <Level column="municipality_id" name="Municipality" nameColumn="municipality_name" uniqueMembers="true" />
        </Hierarchy>
    </Dimension>
    <Dimension name="Geography State">
        <Hierarchy hasAll="true" primaryKey="state_id">
            <View alias="dim_state">
                <SQL>(SELECT distinct(state_id), state_name from dim_municipality)</SQL>
            </View>
            <Level column="state_id" name="State" nameColumn="state_name" uniqueMembers="true" />
        </Hierarchy>
    </Dimension>
    <Cube name="crimes">
        <Annotations>
            <Annotation name="source_name">Secretariado Ejecutivo del Sistema de Seguridad Pública</Annotation>
        </Annotations>
        <Table name="fact_crimes" schema="safety" />
        <Dimension name="Crime Type" foreignKey="crime_type_id">
            <Hierarchy hasAll="true" primaryKey="crime_type_id">
                <Table name="dim_crime_type" schema="safety" />
                <Level column="crime_type_level_1_id" name="Crime Type" nameColumn="crime_type_level_1_name" uniqueMembers="true" />
                <Level column="crime_type_level_2_id" name="Crime Subtype" nameColumn="crime_type_level_2_name" uniqueMembers="true" />
            </Hierarchy>
        </Dimension>
        <DimensionUsage foreignKey="municipality_id" name="Geography" source="Geography" />
        <DimensionUsage foreignKey="date_id" name="Date" source="Date" />
        <Measure aggregator="sum" column="count" name="Incidentes" visible="true" caption="Crimes">
            <Annotations>
                <Annotation name="es_element_caption">Incidencia Delictiva</Annotation>
            </Annotations>
        </Measure>
    </Cube>
</Schema>
~~~~

**Comment by gemathus** [comment]
Also, this is my db structure on `public.dime_date`

~~~~sql
SELECT id,the_year,month_of_year 
FROM public.dim_date 
WHERE (the_year>=2015 AND the_year <= 2019) AND month_of_year<=12 AND day_of_month=1;
~~~~
**id**|**the\_year**|**month\_of\_year**
:-----:|:-----:|:-----:
9132|2015|1
9163|2015|2
9191|2015|3
9222|2015|4
9252|2015|5
9283|2015|6
9313|2015|7
9344|2015|8
9375|2015|9
9405|2015|10
9436|2015|11
9466|2015|12
9497|2016|1
9528|2016|2
9557|2016|3
9588|2016|4
9618|2016|5
9649|2016|6
9679|2016|7
9710|2016|8
9741|2016|9
9771|2016|10
9802|2016|11
9832|2016|12
9863|2017|1
9894|2017|2
9922|2017|3
9953|2017|4
9983|2017|5
10014|2017|6
10044|2017|7
10075|2017|8
10106|2017|9
10136|2017|10
10167|2017|11
10197|2017|12
10228|2018|1
10259|2018|2
10287|2018|3
10318|2018|4
10348|2018|5
10379|2018|6
10409|2018|7
10440|2018|8
10471|2018|9
10501|2018|10
10532|2018|11
10562|2018|12
10593|2019|1
10624|2019|2
10652|2019|3
10683|2019|4
10713|2019|5
10744|2019|6
10774|2019|7
10805|2019|8
10836|2019|9
10866|2019|10
10897|2019|11
10927|2019|12

So I'm not sure where it could have gone wrong. 

If I do individual cuts on each year, the month names appear just fine.

**Comment by frabarz** [comment]
I checked with a colleague and he says your problem is the month_of_year column. You have to create a new column with a unique ID for the combo year-month, like

| id   | year | month | yearmonth |
|------|------|-------|-----------|
| 9132 | 2015 | 1     | 201501    |
| 9163 | 2015 | 2     | 201502    |

Then use the combined id (yearmonth) for the `Level.column` and the original id (month) for the caption (like in your CaptionExpression)

**Comment by gemathus** [comment]
Makes a lot of sense. Thank you both! I'll close the issue myself.

**Comment by gemathus** [comment]
@frabarz  :+1: 

![Screenshot from 2019-09-12 12-53-48](https://user-images.githubusercontent.com/10574406/64808258-7f3e2f00-d55c-11e9-92ef-a5841007f659.png)
