### ISSUE TITLE
add support for passing tokens for tesseract cubes

### ISSUE THREAD

**Issue by jspeis** [Datawheel/olap-client#7]
Now that tesseract supports JWTs would be nice if the requests could add `x-tesseract-jwt-token` as either a header or URL query parameter to authenticate requests

**Comment by frabarz** [comment]
The module now allows to set full AxiosRequestConfig params via the `IDataSource#setRequestConfig` method. It also exposes a `IDataSource.axiosInstance` that can be interacted with.
